Config:
    AWS_PROFILE: default  # Name of your AWS profile from .aws/credentials
    DESTINATION_NAME: SensorAppDestination  # Sidewalk destination used for uplink traffic routing
    HARDWARE_PLATFORM: ALL  # Available values: NORDIC, TI, SILABS or ALL
    USERNAME: null
    PASSWORD: null
    INTERACTIVE_MODE: True
Outputs:
    DEVICE_PROFILE_ID: 220ed912-8a41-4cfe-a98e-9ca4eab1c359
    WEB_APP_URL: null
_Paths:
    PROVISION_SCRIPT_DIR: tools/provision
    SILABS_COMMANDER_TOOLS_DIR: null  # Not needed if Silabs Commander is already in system Path. Only needed for SILABS.
